name: CI

# Controls when the action will run.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Create Sandstorm Package
        env:
          SPK_KEY: ${{ secrets.SPK_KEY }}
        run: |
          wget https://raw.githubusercontent.com/sandstorm-io/sandstorm/master/install.sh
          chmod +x install.sh && sudo ./install.sh -d
          sudo ./build
          echo $SPK_KEY | base64 -d > ~/.sandstorm-keyring
          sudo spk pack monica.spk
          
      - name: Run smoke test
        uses: cypress-io/github-action@v2.7.0
        with:
          start: sudo spk dev
          browser: chrome        
